[project]
name = "karpathy"
version = "0.1.0"
description = "Andrej Karpathy lectures"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "graphviz>=0.21",
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "torch>=2.8.0",
]
